global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: WARN
  format: common
api:
  dashboard: true
  insecure: true
ping: {}
accessLog: {}
providers:
  file:
    watch: true
    directory: E:\traefik\config
    debugLogGeneratedTemplate: true
entryPoints:
  http:
    address: :80
  https:
    address: :443
experimental:
  localPlugins:
    example:
      moduleName: github.com/traefik/plugindemo
